basePath: /
definitions:
  errorx.Error:
    properties:
      detail:
        example: Your current balance is 30, but that costs 50.
        type: string
      instance:
        example: /account/12345/msgs/abc
        type: string
      status:
        example: 403
        type: integer
      title:
        example: You do not have enough credit.
        type: string
      type:
        example: https://example.com/probs/out-of-credit
        type: string
    type: object
  model.CreateMessageDTO:
    properties:
      msg:
        type: string
    required:
    - msg
    type: object
  model.MessageDTO:
    properties:
      id:
        type: string
      msg:
        type: string
    type: object
info:
  contact: {}
  description: Provide an interface to HTTP responses.
  title: IskayPet gorest-api
  version: v1.
paths:
  /messages:
    get:
      description: Get a message.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MessageDTO'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errorx.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorx.Error'
      summary: Get a message
      tags:
      - Custom
    post:
      consumes:
      - application/json
      description: Create a new message.
      parameters:
      - description: Message details
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/model.CreateMessageDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.MessageDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errorx.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errorx.Error'
      summary: Create a new message
      tags:
      - Custom
swagger: "2.0"
