apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oms
namePrefix: gorest-api--
generatorOptions:
  disableNameSuffixHash: true

resources:
- service.yaml
- ingress.yaml
- deployment.yaml
- config.yaml

configMapGenerator:
- behavior: merge
  name: config

labels:
- includeSelectors: true
  pairs:
    name: gorest-api
