// Code generated by mockery. DO NOT EDIT.

package services

import (
	mock "github.com/stretchr/testify/mock"
	model "gitlab.com/iskaypetcom/digital/oms/api-core/gorest-api/src/app/model"
	paging "gitlab.com/iskaypetcom/digital/oms/api-core/gorest-api/src/app/model/paging"
)

// MockIUsersService is an autogenerated mock type for the IUsersService type
type MockIUsersService struct {
	mock.Mock
}

type MockIUsersService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUsersService) EXPECT() *MockIUsersService_Expecter {
	return &MockIUsersService_Expecter{mock: &_m.Mock}
}

// GetUsers provides a mock function with given fields: page, perPage
func (_m *MockIUsersService) GetUsers(page int, perPage int) (*paging.PagedResultDTO[model.UserDTO], error) {
	ret := _m.Called(page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 *paging.PagedResultDTO[model.UserDTO]
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (*paging.PagedResultDTO[model.UserDTO], error)); ok {
		return rf(page, perPage)
	}
	if rf, ok := ret.Get(0).(func(int, int) *paging.PagedResultDTO[model.UserDTO]); ok {
		r0 = rf(page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paging.PagedResultDTO[model.UserDTO])
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUsersService_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockIUsersService_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - page int
//   - perPage int
func (_e *MockIUsersService_Expecter) GetUsers(page interface{}, perPage interface{}) *MockIUsersService_GetUsers_Call {
	return &MockIUsersService_GetUsers_Call{Call: _e.mock.On("GetUsers", page, perPage)}
}

func (_c *MockIUsersService_GetUsers_Call) Run(run func(page int, perPage int)) *MockIUsersService_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockIUsersService_GetUsers_Call) Return(_a0 *paging.PagedResultDTO[model.UserDTO], _a1 error) *MockIUsersService_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUsersService_GetUsers_Call) RunAndReturn(run func(int, int) (*paging.PagedResultDTO[model.UserDTO], error)) *MockIUsersService_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUsersService creates a new instance of MockIUsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUsersService {
	mock := &MockIUsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
