apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml

patches:
- path: patches/config.yaml
- path: patches/ingress/tls.yaml
  target:
    name: ingress
